"$schema" = "schemas/schema.json"
[default]
description = """
This permission set configures which
biometry features are by default exposed.

#### Granted Permissions

It allows acccess to all biometry commands.

"""

permissions = ["allow-authenticate", "allow-status", "allow-has-data", "allow-get-data", "allow-set-data", "allow-remove-data"]
